baseurl = "/"
languageCode = "en-us"
title = "A Hugo website"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Facebook"
    url = "https://www.facebook.com/eugene100hickey"
    weight = 2
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/eugene100hickey"
    weight = 3
[[menu.main]]
    name = "TU Dublin"
    url = "https://www.ittdublin.ie"
    weight = 4
[params]
    description = "A website built through Hugo and blogdown."
    customCSS = ["css/erum.css"]
    
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "eRum2020.png"
    width = 50
    height = 50
    alt = "Logo"
enableEmoji = true
